### PR TITLE
Change citation bibtex

### PR DESCRIPTION
**Pull request by agricolamz**
I guess this is the right way to write a `.bibtex` entry.

### CODE REVIEW

**Comment by tzakharko** [comment]
What LaTeX configuration are you experiencing issues with? The usual recommended toolchains (xelatex/lualatex + biber) have been unicode for a while.

**Comment by agricolamz** [comment]
I expected that pure pdflatex will crash with that kind of usage of unicode. I guess `\usepackage[utf8]{inputenc}` is just another way of solving the problem.

**Comment by tzakharko** [comment]
UTF8 has been the default input encoding for LaTeX 2e since April 2018, so it should work even with pdflatex. It is possible that some folks might have their reasons for running an older system, but I would really prefer to keep things relatively modern unless it can be demonstrated that this causes significant issues in real world usage. 

I will therefore reject this PR for now, until someone can come up with a good reason why we should avoid UTF-8 here. 

Thanks!

**Comment by agricolamz** [comment]
Ok, make sense.

**Pull request closed without merging**
